Rebuild for github.com/wtsi-ssg/wrstat@v6
wtsi-hgi/wrstat-ui pull request #11
Opened 2024-12-12 14:11 UTC by mjkw31

2025-01-13 10:32 UTC, sb10 requested changes
Thanks, this represents a ton of work, well implemented! Please do the changes per the review comments, and also any trivial changes requested in the recent jira cards. Larger changes can wait for a new PR after this is merged.

2025-01-13 10:32 UTC, sb10 commented on summary/dirguta/dirguta.go
> +// Add is a github.com/wtsi-ssg/wrstat/stat Operation. It will break path in to
Update all docs like this to mention the correct pkg

2025-01-13 10:32 UTC, sb10 commented on summary/dirguta/dirguta.go
> +// "Access" times are actually considered to be the greatest of atime, mtime and
I think the exact details of how this works has changed; check and update

2025-01-13 10:32 UTC, sb10 commented on summary/dirguta/dirguta.go
> +func InfoToType(info *summary.FileInfo) (db.DirGUTAFileType, bool) {
Document all public things

2025-01-13 10:32 UTC, sb10 commented on summary/summariser.go
> +package summary
Add boilerplate and document public things

2025-01-13 10:32 UTC, sb10 commented on summary/summariser_test.go
> +package summary
Add boilerplate

2025-01-13 10:32 UTC, sb10 commented on summary/summary.go
> +// add will increment our count and add the given size to our size.
Capital A on the Add funcs, and document all other public things

2025-01-13 14:11 UTC, mjkw31 commented on cmd/summarise.go
> +		if r, err = pgzip.NewReader(f); err != nil {
It won't be at the moment, as it's CPU bound; this may be worth revisiting once we eliminate the unnecessary CPU overhead.

In that case, I would prefer to in stdin for this, anyway, which already supported by setting the input filename to '-'.

2025-01-13 15:35 UTC, sb10 commented on cmd/summarise.go
> +		if r, err = pgzip.NewReader(f); err != nil {
If it's cpu bound, pigz could improve the speed by decompressing faster.
STDIN doesn't allow for supplying multiple inputs, which is one of the feature requests.

2025-01-13 16:05 UTC, mjkw31 commented on cmd/summarise.go
> +		if r, err = pgzip.NewReader(f); err != nil {
It's not bound on the decompress; it's all in the summarisers.

Also, unless we need to differentiate the different input streams for some reason, you can definitely supply multiple inputs via STDIN.

2025-01-14 11:03 UTC, sb10 commented on cmd/summarise.go
> +		if r, err = pgzip.NewReader(f); err != nil {
I tried it, and pigz used a bit less cpu time and a bit more wall time. So yeah, it's fine as it is.

2025-01-14 11:07 UTC, sb10 approved these changes

2025-01-14 11:13 UTC, merged