Display new information from dgutas for a league table
wtsi-hgi/wrstat-ui pull request #5
Opened 2024-10-25 15:10 UTC by rk1274

2024-10-25 16:24 UTC, mjkw31 requested changes

2024-10-25 16:24 UTC, mjkw31 commented on go.mod
> +replace github.com/wtsi-ssg/wrstat/v5 => /nfs/users/nfs_r/rk18/src/wrstat
This is probably wrong.

2024-10-25 16:24 UTC, mjkw31 commented on server/static/wrstat/src/Filter.tsx
> +				<label htmlFor={`age`}>Age</label>
[htmlFor](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for) (which can just be set with a normal string) needs to match the ID of the input element that the label is for. You'll need to add an ID attribute to the select element for it to be linked.

2024-10-25 16:24 UTC, mjkw31 commented on server/static/wrstat/src/App.tsx
> +				Age: (rowAge: number) => {
It doesn't overly matter, but this can just be:

```
			Age: (rowAge: number) => rowAge === age,
```

NB: Should always use triple equals in JS unless you know why you're not.

2024-10-25 16:24 UTC, mjkw31 commented on server/static/wrstat/src/Filter.tsx
> +					<option value="9">unchanged files (1 month)</option>
Indent needs correcting here.

2024-10-25 16:24 UTC, mjkw31 commented on server/static/wrstat/src/TreeDetails.tsx
> +					<td><div>{details.groups ? details.groups.join(", "): ""}</div></td>
This is fine, but it'd be a bit less stutter-y as:

```
				<td><div>{details?.groups.join(", ") ?? ""}</div></td>
```

Take a look at [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and [Nullish Coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing).

2024-10-30 10:11 UTC, mjkw31 submitted a review, later dismissed
LGTM.

2024-10-30 15:15 UTC, mjkw31 requested changes

2024-10-30 15:15 UTC, mjkw31 commented on server/static/wrstat/src/History.tsx
> +		if (history.length === 0 || isUser || age != 0) {
This age comparison should either be `age !== 0` (strict not equality) or just `age` (if you don't care about the type, just that it's truthy).

2024-10-30 15:57 UTC, mjkw31 approved these changes

2024-10-31 09:38 UTC, sb10 approved these changes

2024-10-31 09:39 UTC, merged